name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checkout this repo, so you can run an 'npm install'
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: ".lighthouserc.json"
          temporaryPublicStorage: true
