name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checkout this repo, so you can run an 'npm install'
      - name: Lighthouse CI
        uses: actions/setup-python@v1
        with:
          urls: |
            https://en.qa.whofreebasics.org/
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
  
