name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checkout this repo, so you can run an 'npm install'
      - uses: actions/setup-node@v1
      - run: npm install && npm install -g @lhci/cli@0.4.x
      - run: npm run build # needed to install your Lighthouse Plugin
      - run: lhci autorun
